name: Release dev chanel

defaults:
  run:
    shell: bash

env:
  CI: true

on:
  schedule:
    # Run at midnight every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  ci-dev:
    name: CI

    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup node cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Bootstrap
        run: npm run bootstrap

      - name: Lint scripts
        run: npm run eslint

      - name: Lint styles
        run: npm run sasslint

      - name: Check docs
        run: npm docs:check

      - name: Build themes for dist
        run: |
          npm run dart:flat
          npm run dart:swatches
          npm run sass:flat
          npm run sass:swatches
